title: korpinen.dev
description: HW/FW/SW
author: Pekka Korpinen
github_username:  pkorpine
linkedin_username: korpinen

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore
  - .github
